services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      #- ./keycloak/configuration:/opt/keycloak/standalone/configuration:rw
      - ./keycloak/data:/opt/keycloak/data:rw
      - ./keycloak/themes:/opt/keycloak/themes:rw
    ports:
      - 8081:8080
    command:
      - start-dev --spi-theme-static-max-age=-1 --spi-theme-cache-themes=false --spi-theme-cache-templates=false
